# Docker Swarm Stack for GitHub Agent
# Deploy across your laptop + Raspberry Pi cluster

version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.ollama==true
      resources:
        limits:
          memory: 3G
          cpus: '1.5'
        reservations:
          memory: 2G
          cpus: '1.0'
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - agent-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  github-agent:
    image: node:20-slim
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    ports:
      - "3001:3000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - NODE_ENV=production
      - GITHUB_REPO=Benhaswings/ai-agent
      - PORT=3000
      - TELEGRAM_CHAT_ID=1569185905
    env_file:
      - .env
    volumes:
      - type: bind
        source: /home/ben/github-agent
        target: /app
      - type: bind
        source: /home/ben/github-agent/.env
        target: /app/.env
        read_only: true
    working_dir: /app
    command: >
      bash -c "npm install --legacy-peer-deps && source .env && node event-handler/server.js"
    networks:
      - agent-network
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  processor:
    image: node:20-slim
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - NODE_ENV=production
      - GITHUB_REPO=Benhaswings/ai-agent
      - TELEGRAM_CHAT_ID=1569185905
    env_file:
      - .env
    volumes:
      - type: bind
        source: /home/ben/github-agent
        target: /app
      - type: bind
        source: /home/ben/github-agent/.env
        target: /app/.env
        read_only: true
    working_dir: /app
    command: >
      bash -c "npm install --legacy-peer-deps && source .env && ./scripts/local-processor.sh"
    networks:
      - agent-network
    depends_on:
      - ollama

  # Visualizer for Swarm (optional - shows container distribution)
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - agent-network

volumes:
  ollama-models:
    driver: local

networks:
  agent-network:
    driver: overlay
    attachable: true
